app = 'common'

name = "palindrome"

backend = 'local'

[param.module.count1]
type = 'command'
arguments = [ 'ping', 'word1' ]

[param.module.count2]
type = 'command'
arguments = 'word2'

[param.module.sum]
type = 'command'

[param.splitter]
type = 'sequence'
param = { start = 0, step = 100, number = 10 }
