#!/bin/sh

if [ $# != 1 ]; then
    echo 'Need 1 arguments!'
    exit 1
fi

task_sub_id_start=$1

cd `dirname $0`
launch_dir=`pwd`

task_work_root="${launch_dir}/jobs"

task_sub_id=${task_sub_id_start}
job_work_root="${task_work_root}/${task_sub_id_start}"

mkdir -p ${job_work_root}
cd ${job_work_root}

${launch_dir}/main/bootstrap.sh ${task_sub_id} ${job_work_root}
